/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

/**
 *
 * @author cattwinlow
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        //para que la interfaz see ajuste al centro de la pantalla al iniciar
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IniciarSesion = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        TextUser = new javax.swing.JLabel();
        TextPass = new javax.swing.JLabel();
        InPass = new javax.swing.JPasswordField();
        InUser = new javax.swing.JFormattedTextField();
        IconAucol = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IniciarSesion.setText("Iniciar Sesión");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TextUser.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        TextUser.setForeground(new java.awt.Color(255, 255, 255));
        TextUser.setText("Clave");
        getContentPane().add(TextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        TextPass.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        TextPass.setForeground(new java.awt.Color(255, 255, 255));
        TextPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextPass.setText("Usuario");
        getContentPane().add(TextPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        InPass.setBackground(new java.awt.Color(153, 0, 0));
        InPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InPassActionPerformed(evt);
            }
        });
        getContentPane().add(InPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 120, 20));

        InUser.setEditable(false);
        InUser.setBackground(new java.awt.Color(153, 0, 0));
        InUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InUserActionPerformed(evt);
            }
        });
        getContentPane().add(InUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 120, -1));

        IconAucol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/IconAuc.jpg"))); // NOI18N
        IconAucol.setText("jLabel1");
        getContentPane().add(IconAucol, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 100, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fondo.jpg"))); // NOI18N
        Background.setOpaque(true);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void InPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InPassActionPerformed

    private void InUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel IconAucol;
    private javax.swing.JPasswordField InPass;
    private javax.swing.JFormattedTextField InUser;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel TextPass;
    private javax.swing.JLabel TextUser;
    // End of variables declaration//GEN-END:variables
}
